# Site settings
title: CHeese
description: A test template for Jekyll
keywords: Modern, Blogging, Fun
author: Azeril
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
